=== qnNAI/JavaTraining/part02task03XML/src/main/resources/xml/Entity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/entities"
        xmlns:tns="http://www.training.by/entities"
        elementFormDefault="qualified">
    <element name="entities">
        <complexType>
            <sequence>
                <element ref="tns:entity"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <element name="entity" type="tns:Entity" abstract="true"></element>
    <element name="user" type="tns:User" substitutionGroup="tns:entity"></element>
    <element name="product" type="tns:Product" substitutionGroup="tns:entity"></element>
    <element name="purchase" type="tns:Purchase" substitutionGroup="tns:entity"></element>

    <complexType name="Entity">
        <attribute name="id" type="int" use="required"></attribute>
    </complexType>

    <complexType name="User">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="username" type="string"/>
                    <element name="password" type="string"/>
                    <element name="name" type="string"/>
                    <element name="surname" type="string"/>
                    <element name="patronymic" type="string"/>
                    <element name="email" type="string"/>
                    <element name="phone" type="string"/>
                    <element name="purchase" type="tns:Purchase" minOccurs="1" maxOccurs="unbounded"/>
                </sequence>
                <attribute name="role" use="required">
                    <simpleType>
                        <restriction base="int">
                            <enumeration value="0"></enumeration>
                            <enumeration value="1"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="state" use="required">
                    <simpleType>
                        <restriction base="int">
                            <enumeration value="0"></enumeration>
                            <enumeration value="1"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Product">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="name" type="string"></element>
                    <element name="price" type="double"></element>
                    <element name="description" type="string"></element>
                    <element name="image_path" type="string"></element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Purchase">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="product" type="tns:Product" minOccurs="1" maxOccurs="unbounded"></element>
                    <element name="address" type="string"></element>
                    <element name="finalprice" type="double"></element>
                    <element name="date" type="string"></element>
                    <element name="amount" type="int"></element>
                </sequence>
                <attribute name="state" use="required">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="изготавливается"></enumeration>
                            <enumeration value="готов"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
                <attribute name="obtainingMethod" use="required">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="доставка"></enumeration>
                            <enumeration value="самовывоз"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

</schema>

=== qnNAI/JavaTraining/part02task03XML/src/main/resources/xml/Entity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.training.by/entities"
       xsi:schemaLocation="http://www.training.by/entities Entity.xsd">
    <user  id="1" role="1" state="0">
        <username>vasya</username>
        <password>12345</password>
        <name>Vasiliy</name>
        <surname>Terkin</surname>
        <patronymic>Vasilich</patronymic>
        <email>vasya@mail.ru</email>
        <phone>1112233</phone>
        <purchase id="1" state="готов" obtainingMethod="самовывоз">
            <product id="1">
                <name>cat</name>
                <price>500</price>
                <description>cat</description>
                <image_path>cat.jpg</image_path>
            </product>
            <address>1 Dunbar Ave. Chesterton, IN 46304</address>
            <finalprice>550</finalprice>
            <date>20-12-2000</date>
            <amount>1</amount>
        </purchase>
        <purchase id="5" state="готов" obtainingMethod="самовывоз">
            <product id="5">
                <name>bear</name>
                <price>1000</price>
                <description>bear</description>
                <image_path>bear.jpg</image_path>
            </product>
            <address>76 Chapel St.Saint Cloud, MN 56301</address>
            <finalprice>300</finalprice>
            <date>12-06-2012</date>
            <amount>5</amount>
        </purchase>
    </user>

    <user  id="2" role="1" state="1">
        <username>petya</username>
        <password>54321</password>
        <name>Petr</name>
        <surname>Shishka</surname>
        <patronymic>Petrov</patronymic>
        <email>petya@mail.ru</email>
        <phone>3332211</phone>
        <purchase id="2" state="изготавливается" obtainingMethod="доставка">
            <product id="2">
                <name>dog</name>
                <price>1000</price>
                <description>dog</description>
                <image_path>dog.jpg</image_path>
            </product>
            <product id="3">
                <name>pig</name>
                <price>2000</price>
                <description>pig</description>
                <image_path>pig.jpg</image_path>
            </product>
            <address>7943 Fulton Rd.Bellmore, NY 11710</address>
            <finalprice>3000</finalprice>
            <date>20-07-2000</date>
            <amount>5</amount>
        </purchase>
    </user>

    <user  id="2" role="1" state="1">
        <username>JackBlack</username>
        <password>66611</password>
        <name>Jack</name>
        <surname>Smith</surname>
        <patronymic>--</patronymic>
        <email>jackBlack@mail.ru</email>
        <phone>6661122</phone>
        <purchase id="4" state="изготавливается" obtainingMethod="доставка">
            <product id="4">
                <name>fish</name>
                <price>8000</price>
                <description>fish</description>
                <image_path>fish.jpg</image_path>
            </product>
            <address>305 Purple Finch Court Olney, MD 20832</address>
            <finalprice>8000</finalprice>
            <date>07-10-2013</date>
            <amount>5</amount>
        </purchase>
    </user>

    <user  id="2" role="1" state="1">
        <username>Mikky</username>
        <password>66611</password>
        <name>Mike</name>
        <surname>Johnson</surname>
        <patronymic>--</patronymic>
        <email>mikk@mail.ru</email>
        <phone>1745522</phone>
        <purchase id="6" state="готов" obtainingMethod="самовывоз">
            <product id="6">
                <name>ball</name>
                <price>700</price>
                <description>ball</description>
                <image_path>ball.jpg</image_path>
            </product>
            <address>894 Tarkiln Hill St. Stafford, VA 22554</address>
            <finalprice>800</finalprice>
            <date>11-11-2011</date>
            <amount>5</amount>
        </purchase>
    </user>

    <user  id="2" role="1" state="1">
        <username>Mikky</username>
        <password>66611</password>
        <name>Steve</name>
        <surname>Jones</surname>
        <patronymic>--</patronymic>
        <email>stevej@mail.ru</email>
        <phone>5542628</phone>
        <purchase id="7" state="готов" obtainingMethod="доставка">
            <product id="7">
                <name>car</name>
                <price>5000</price>
                <description>car</description>
                <image_path>car.jpg</image_path>
            </product>
            <address>894 Tarkiln Hill St. Stafford, VA 22554</address>
            <finalprice>5500</finalprice>
            <date>30-10-2009</date>
            <amount>5</amount>
        </purchase>
    </user>
</entities>

=== qnNAI/JavaTraining/part02task03XML/target/classes/xml/Entity.xml
<?xml version="1.0" encoding="UTF-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.training.by/entities"
       xsi:schemaLocation="http://www.training.by/entities Entity.xsd">
    <user  id="1" role="1" state="1">
        <username>vasya</username>
        <password>12345</password>
        <name>Vasiliy</name>
        <surname>Terkin</surname>
        <patronymic>Vasilich</patronymic>
        <email>vasya@mail.ru</email>
        <phone>1112233</phone>
        <purchase id="1" state="готов" obtainingMethod="самовывоз">
            <product id="1">
                <name>prod1</name>
                <price>500</price>
                <description>just a product</description>
                <image_path>aaa.jpg</image_path>
            </product>
            <address>wwwww</address>
            <finalprice>550</finalprice>
            <date>20-20-2000</date>
            <amount>1</amount>
        </purchase>
    </user>

    <user  id="2" role="1" state="1">
        <username>petya</username>
        <password>54321</password>
        <name>Petr</name>
        <surname>Shishka</surname>
        <patronymic>Petrov</patronymic>
        <email>petya@mail.ru</email>
        <phone>3332211</phone>
        <purchase id="2" state="изготавливается" obtainingMethod="доставка">
            <product id="2">
                <name>prod2</name>
                <price>1000</price>
                <description>just a product 2</description>
                <image_path>bbb.jpg</image_path>
            </product>
            <product id="3">
                <name>prod3</name>
                <price>2000</price>
                <description>just a product 3</description>
                <image_path>333.jpg</image_path>
            </product>
            <address>qqqq</address>
            <finalprice>3000</finalprice>
            <date>20-07-2000</date>
            <amount>5</amount>
        </purchase>
    </user>
</entities>
